**Name:** Ivanne Dave L. Bayer <br>
**Date:** December 2023 <br>
**Course:** Discrete Structure III <br>

---

# <font color=red> CODE CHALLENGES </font>
---
### Instruction
1. Push your solutions to your github account.
3. Deadline is before finals.
---
1. Without the use of any python libraries or modules, develop a function that can perform matrix addition, given two numpy matrices.

In [1]:
def matrix_addition(matrix_a, matrix_b):
    # Check if the matrices have the same dimensions
    if len(matrix_a) != len(matrix_b) or len(matrix_a[0]) != len(matrix_b[0]):
        raise ValueError("Matrices must have the same dimensions for addition")

    # Initialize an empty matrix for the result
    result = []

    # Iterate through rows and columns, adding corresponding elements
    for i in range(len(matrix_a)):
        row = []
        for j in range(len(matrix_a[0])):
            row.append(matrix_a[i][j] + matrix_b[i][j])
        result.append(row)

    return result

# Example usage:
matrix_a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix_b = [
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
]

result_matrix = matrix_addition(matrix_a, matrix_b)
for row in result_matrix:
    print(row)

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


2. Without the use of any python libraries or modules, develop a function that can multiply two numpy matrices.

In [2]:
def matrix_multiply(mat1, mat2):
    # Check if the matrices can be multiplied
    if len(mat1[0]) != len(mat2):
        raise ValueError("Number of columns in the first matrix must be equal to the number of rows in the second matrix.")

    # Get dimensions of the matrices
    rows_mat1 = len(mat1)
    cols_mat1 = len(mat1[0])
    cols_mat2 = len(mat2[0])

    # Initialize result matrix with zeros
    result = [[0 for _ in range(cols_mat2)] for _ in range(rows_mat1)]

    # Perform matrix multiplication
    for i in range(rows_mat1):
        for j in range(cols_mat2):
            for k in range(cols_mat1):
                result[i][j] += mat1[i][k] * mat2[k][j]

    return result

# Example usage:
matrix1 = [[1, 2, 3], [4, 5, 6]]
matrix2 = [[7, 8], [9, 10], [11, 12]]

result_matrix = matrix_multiply(matrix1, matrix2)
for row in result_matrix:
    print(row)

[58, 64]
[139, 154]


3. The rule of distributivity states that given two matrices $A$ and $B$ and a scalar, $k$, then $k(A+B)=kA+kB$. Instead of writing a proof mathematically, develop two codes for $k(A+B)$ and $kA+kB$.

In [3]:
import numpy as np

# Define matrices A and B
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Define scalar k
k = 2

# Calculate k(A + B)
result1 = k * (A + B)

# Calculate kA + kB
result2 = k * A + k * B

# Print the results
print("k(A + B):")
print(result1)

print("\nkA + kB:")
print(result2)

k(A + B):
[[12 16]
 [20 24]]

kA + kB:
[[12 16]
 [20 24]]


4. Without using a python library or modules develop a function that can extract the diagonal of a numpy matrix.

In [4]:
def extract_diagonal(matrix):
    """
    Extracts the diagonal elements of a matrix.

    Parameters:
    - matrix: A 2D list representing the matrix.

    Returns:
    - diagonal: A list containing the diagonal elements of the matrix.
    """
    diagonal = []
    rows = len(matrix)
    cols = len(matrix[0]) if matrix else 0

    # Check if the matrix is square
    if rows != cols:
        raise ValueError("Input matrix must be square.")

    for i in range(rows):
        for j in range(cols):
            if i == j:
                diagonal.append(matrix[i][j])

    return diagonal

# Example usage:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

result = extract_diagonal(matrix)
print(result)

[1, 5, 9]


5. Without using a python library or modules develop a function that can find a trace of a numpy matrix.

In [5]:
def matrix_trace(matrix):
    # Check if the matrix is square
    rows, cols = len(matrix), len(matrix[0])
    if rows != cols:
        raise ValueError("Input matrix must be square for trace calculation")

    # Calculate the trace
    trace = 0
    for i in range(rows):
        trace += matrix[i][i]

    return trace

# Example usage:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

result = matrix_trace(matrix)
print("Trace of the matrix:", result)

Trace of the matrix: 15


---
# <font color=red> Assignment 3 </font>
---
Instructions
1. Write your solution in latex.
2. Push your solutions to your github account.
3. Deadline is before finals.
---

1. Solve X given that:
$
\begin{equation}
    A =
    \begin{bmatrix}
    1 & 2 \\
    3 & 4 \\
    \end{bmatrix},
    B =
    \begin{bmatrix}
    -1 & 0 \\
    1 & 1 \\
    \end{bmatrix}
\end{equation}
$
<br>

- $3X = A-2B$
    - Multiply $B$ by 2
    $
     \begin{equation}
     2
        \begin{bmatrix}
            -1 & 0\\
            1 & 1\\
        \end{bmatrix}
        \xrightarrow[]{}
        \begin{bmatrix}
            -2 & 0\\
            2 & 2\\
        \end{bmatrix}
    \end{equation}
    $ 
    - Subtract 2 $B$ from $A$
     \begin{equation}
        \begin{bmatrix}
            1 & 2\\
            3 & 4\\
        \end{bmatrix}
        -2 
        \begin{bmatrix}
            -2 & 0\\
            2 & 2\\
        \end{bmatrix}
        \xrightarrow[]{}
        \begin{bmatrix}
            3 & 2\\
            1 & 2\\
        \end{bmatrix}
    \end{equation}
    - Divide the result by 3 to isolate $X$
     \begin{equation}
        \frac{1}{3}
        \begin{bmatrix}
            3 & 2\\
            1 & 2\\
        \end{bmatrix}
        \xrightarrow[]{}     
        \begin{bmatrix}
            1 & \frac{2}{3}\\
            \frac{1}{3} & \frac{2}{3}\\
        \end{bmatrix}
    \end{equation}

In [5]:
import numpy as np

# Define matrices A and B
A = np.array([[1, 2], [3, 4]])
B = np.array([[-1, 0], [1, 1]])

# Calculate 2B
two_B = 2 * B

# Calculate A - 2B
result = A - two_B

# Solve for X by dividing the result by 3
X = result / 3

# Print the result
print("Matrix X:")
print(X)

Matrix X:
[[1.         0.66666667]
 [0.33333333 0.66666667]]


- $2(A-B+2X) = 3(X-B)$
    - Distribute the scalar values 
    <br>
    $2A - 2B + 4X = 3X - 3B$
    - Combine like terms
    <br>
    $2A + B = X$
    - Now we can substitute the given matrices $A$ and $B$ to find $X$
     \begin{equation}
        X
        \xrightarrow[]{}
        2A + B
        \xrightarrow[]{}
        2
        \begin{bmatrix}
            1 & 2\\
            3 & 4\\
        \end{bmatrix}
        +
        \begin{bmatrix}
            -1 & 0\\
            1 & 1\\
        \end{bmatrix}
    \end{equation}
    - Perform the matrix multiplication and addition
     \begin{equation}
        X
        \xrightarrow[]{}
        \begin{bmatrix}
            2 & 4\\
            6 & 8\\
        \end{bmatrix}
        +    
        \begin{bmatrix}
            -1 & 0\\
            1 & 1\\
        \end{bmatrix}
        \xrightarrow[]{}
        \begin{bmatrix}
            1 & 4\\
            7 & 9\\
        \end{bmatrix}
    \end{equation}

In [8]:
import numpy as np

# Define matrices A and B
A = np.array([[1, 2], [3, 4]])
B = np.array([[-1, 0], [1, 1]])

# Calculate X
X = 2 * A + B

# Print the result
print("X:")
print(X)

X:
[[1 4]
 [7 9]]


---

2. Write B as a linear combination of the other matrices, if possible.
$ 
\begin{equation}
A_1 =
\begin{bmatrix}
1 & 2 \\
-1 & 1 \\
\end{bmatrix},
A_2 =
\begin{bmatrix}
0 & 1 \\
2 & 1 \\
\end{bmatrix},
B =
\begin{bmatrix}
2 & 5 \\
0 & 3 \\
\end{bmatrix}
\end{equation}
$

In [14]:
import numpy as np

# Define matrices A1, A2, and B
A1 = np.array([[1, 2], [-1, 1]])
A2 = np.array([[0, 1], [2, 1]])
B = np.array([[2, 5], [0, 3]])

# Set up the system of equations
coefficients_matrix = np.array([[1, 2], [-1, 1]])
coefficients_vector = np.array([2, 3])

# Solve the system of equations
solution = np.linalg.solve(coefficients_matrix, coefficients_vector)

# Extract coefficients x and y
x, y = solution

# Express B as a linear combination of A1 and A2
linear_combination = x * A1 + y * A2

# Print the results
print(f"Coefficients (x, y): ({x}, {y})")
print("Linear Combination of A1 and A2 to obtain B:")
print(linear_combination)

Coefficients (x, y): (-1.3333333333333335, 1.6666666666666667)
Linear Combination of A1 and A2 to obtain B:
[[-1.33333333 -1.        ]
 [ 4.66666667  0.33333333]]


$
\begin{equation}
A_1 =
\begin{bmatrix}
1 & 0 \\
0 & 1 \\
\end{bmatrix},
A_2 =
\begin{bmatrix}
0 & 1 \\
1 & 0 \\
\end{bmatrix},
A_3 =
\begin{bmatrix}
1 & -1 \\
1 & 1 \\
\end{bmatrix},
B =
\begin{bmatrix}
2 & 5 \\
0 & 3 \\
\end{bmatrix}
\end{equation}
$
<br>
<br>

---

3. Given the following:
$
\begin{equation}
A =
\begin{bmatrix}
1 & 2 \\
2 & 6 \\
\end{bmatrix},
b_1 =
\begin{bmatrix}
3 \\
5 \\
\end{bmatrix},
b_2 =
\begin{bmatrix}
-1 \\
2 \\
\end{bmatrix},
b_3 =
\begin{bmatrix}
2 \\
0 \\
\end{bmatrix}
\end{equation}
$
- Find $A^{-1}$, and use this to solve for $Ax=b_1,Ax=b_2,Ax=b_3$
- Solve all three linear systems by row reducing the augmented matrix:
$
\begin{equation}
\begin{bmatrix}
\begin{array}{c|ccc}
A &
b_1 &
b_2 &
b_3 \\
\end{array}
\end{bmatrix}
\end{equation}
$

---

4. In each given, determine if $b$ in in $col(A)$, and $w$ is in $row(A)$
$
\begin{equation}
A =
\begin{bmatrix}
1 & 0 & -1 \\
1 & 1 & 1 \\
\end{bmatrix},
b =
\begin{bmatrix}
3 \\
2 \\
\end{bmatrix},
w =
\begin{bmatrix}
-1 &
1 &
1
\end{bmatrix},
\end{equation}
$
$
\begin{equation}
A =
\begin{bmatrix}
1 & 1 & -1 \\
1 & 3 & 0 \\
3 & -1 & -5 \\
\end{bmatrix},
b =
\begin{bmatrix}
1 \\
2 \\
1 \\
\end{bmatrix},
w =
\begin{bmatrix}
1 &
-3 &
-3
\end{bmatrix},
\end{equation}
$

---

5. Find the rank and nullity of:
$
\begin{bmatrix}
2 & 4 & 0 & 0 & 1 \\
6 & 3 & 5 & 1 & 0 \\
1 & 0 & 2 & 2 & 5 \\
1 & 1 & 1 & 1 & 1 \\
\end{bmatrix}
$

$
 \begin{equation}
    \begin{bmatrix}
        2 & 4 & 0 & 0 & 1 \\
        6 & 3 & 5 & 1 & 0 \\
        1 & 0 & 2 & 2 & 5 \\
        1 & 1 & 1 & 1 & 1 \\
    \end{bmatrix}
    \xrightarrow[]{R_2 - 3R_1}
    \begin{bmatrix}
        2 & 4 & 0 & 0 & 1 \\
        0 & -9 & 5 & 1 & -3 \\
        1 & 0 & 2 & 2 & 5 \\
        1 & 1 & 1 & 1 & 1 \\
    \end{bmatrix}
    \xrightarrow[R_4 - \frac{1}{2}R_1]{R_3 - \frac{1}{2}R_1}
    \begin{bmatrix}
        2 & 4 & 0 & 0 & 1 \\
        0 & -9 & 5 & 1 & -3 \\
        0 & 0 & 2 & 2 & 4.5 \\
        0 & -1 & 1 & 1 & 0.5 \\
    \end{bmatrix}
    \xrightarrow[R_4 - 1]{R_3(R_1)}
    \begin{bmatrix}
        2 & 4 & 0 & 0 & 1 \\
        0 & -9 & 5 & 1 & -3 \\
        0 & 0 & 0 & 0 & 4.5 \\
        0 & 0 & 0 & 0 & 0 \\
    \end{bmatrix}
\end{equation}
$
- Rank of the matrix = <font color=red>4</font>
- Nullity of the matrix = (columns - rank) = (5 - 4) = <font color=red>1</font>

In [1]:
import numpy as np

# Define the matrix
matrix = np.array([
    [2, 4, 0, 0, 1],
    [6, 3, 5, 1, 0],
    [1, 0, 2, 2, 5],
    [1, 1, 1, 1, 1]
])

# Find the rank using NumPy's matrix_rank function
rank = np.linalg.matrix_rank(matrix)

# Find the nullity (number of columns - rank)
nullity = matrix.shape[1] - rank

# Print the results
print("Rank of the matrix:", rank)
print("Nullity of the matrix:", nullity)

Rank of the matrix: 4
Nullity of the matrix: 1
